# Generated by Django 3.1.7 on 2021-08-08 18:57

from django.db import migrations


def init_data(apps, schema_editor):
    # Get models
    Language = apps.get_model('core_rc', 'Language')
    Category = apps.get_model('core_rc', 'Category')
    LocalizedCategory = apps.get_model('core_rc', 'LocalizedCategory')

    # Create language
    language_fr = Language.objects.create(short_code='FR')
    language_en = Language.objects.create(short_code='EN')

    language_fr.save()
    language_en.save()

    # Create Category
    category_redstone = Category.objects.create(code='red')
    category_bluid = Category.objects.create(code='bluid')
    category_news = Category.objects.create(code='news')

    category_redstone.save()
    category_bluid.save()
    category_news.save()

    # create LocalizedCategory
    def save_obj(category, language, name):
        LocalizedCategory.objects.create(name=name, language=language, category=category).save()

    save_obj(category_redstone, language_fr, 'Redstone')
    save_obj(category_redstone, language_en, 'Redstone')
    save_obj(category_bluid, language_fr, 'Construction')
    save_obj(category_bluid, language_en, 'Bluid')
    save_obj(category_news, language_fr, 'Nouvelles')
    save_obj(category_news, language_en, 'News')

class Migration(migrations.Migration):

    dependencies = [
        ('core_rc', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_data),
    ]
