# Generated by Django 3.1.7 on 2021-09-04 19:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core_rc', '0002_feed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizedarticle',
            name='author',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='localizedarticle',
            name='translation_source',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
