# Generated by Django 3.1.7 on 2021-09-06 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_rc', '0003_auto_20210904_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizedarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizedarticle', to='core_rc.article'),
        ),
        migrations.AlterField(
            model_name='localizedarticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=42, null=True, unique=True),
        ),
    ]
