# Generated by Django 3.1.7 on 2021-09-18 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_rc', '0004_auto_20210906_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('bonus_modifier', models.FloatField()),
                ('success_message', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='player',
            old_name='language',
            new_name='main_language',
        ),
        migrations.RenameField(
            model_name='playerinfoprovider',
            old_name='uuid_minecraft',
            new_name='uuid_provider',
        ),
        migrations.AddField(
            model_name='donation',
            name='conversion_rate',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='donation',
            name='currency',
            field=models.CharField(default='EUR', max_length=256),
        ),
        migrations.AddField(
            model_name='donation',
            name='gifter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_gifts', to='core_rc.player'),
        ),
        migrations.AddField(
            model_name='donation',
            name='message',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='playerinfoprovider',
            name='previous_name_provider',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core_rc.player'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='refunded_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='PlayerLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('BG', 'Bulgarian'), ('CS', 'Czech'), ('DA', 'Danish'), ('DE', 'German'), ('EL', 'Greek'), ('EN', 'English'), ('ES', 'Spanish'), ('ET', 'Estonian'), ('FI', 'Finnish'), ('FR', 'French'), ('HU', 'Hungarian'), ('IT', 'Italian'), ('JA', 'Japanese'), ('LT', 'Lithuanian'), ('LV', 'Latvian'), ('NL', 'Dutch'), ('PL', 'Polish'), ('PT', 'Portuguese'), ('RO', 'Romanian'), ('RU', 'Russian'), ('SK', 'Slovak'), ('SL', 'Slovenian'), ('SV', 'Swedish'), ('ZH', 'Chinese')], max_length=5)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='core_rc.player')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation', to='core_rc.discount'),
        ),
    ]
