FORMAT: 1A

# API V1 Game

It is a private API version 0.1, it does require an API key of the type: ```\<provider>_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX```

TODO:
- add json schema
- uniformise with object

# Group Player


### List Player [GET /api/v1/player]

+ Response 200 (application/json)
    [
        {
            "id": "player:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX",
            "main_language": "FR",
            "languages": [
                "FR",
                "EN"
            ],
            "username": "lululombard",
            "providers": {
                "minecraft": {
                    "last_username": "lululombard",
                    "previous_username": "LuluQc",
                    "provider_display_name": "Minecraft",
                    "uuid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
                },
                "discord": {
                    "last_username": "lululombard#1337",
                    "previous_username": null,
                    "provider_display_name": "Discord",
                    "uuid": "123456789012345678"
                }
            },
            "attributes": {
                "command_spy": 0,
            }
        },
        ...
    ]

+ Response 429

### Create Player [POST /api/v1/player]

+ Request (application/json)
    + Body
    {
        "main_language": "EN",
        "languages": [
            "FR",
            "EN"
        ],
        "providers": {
            "minecraft": {
                "last_username": "lululombard",
                "previous_username": "LuluQc",
                "provider_display_name": "Minecraft",
                "uuid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
            },
            "discord": {
                "last_username": "lululombard#1337",
                "previous_username": null,
                "provider_display_name": "Discord",
                "uuid": "123456789012345678"
            }
        },
        "attributes": {
            "command_spy": 0
        }
    }

+ Response 201 (application/json)
    {
        "id": "player:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX",
        "main_language": "EN",
        "languages": [
            "FR",
            "EN"
        ],
        "username": "lululombard",
        "providers": {
            "minecraft": {
                "last_username": "lululombard",
                "previous_username": "LuluQc",
                "provider_display_name": "Minecraft",
                "uuid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
            },
            "discord": {
                "last_username": "lululombard#1337",
                "previous_username": null,
                "provider_display_name": "Discord",
                "uuid": "123456789012345678"
            }
        },
        "attributes": {
            "command_spy": 0
        }
    }

+ Response 429

### Get Player [GET /api/v1/player/{uuid}]
+ Parameters
    + uuid: `minecraft:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX` (string, required) - Regex: `(discord|minecraft|player):(\S*)`

+ Response 200 (application/json)
    {
        "id": "player:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX",
        "main_language": "EN",
        "languages": [
            "FR",
            "EN"
        ],
        "username": "lululombard",
        "providers": {
            "minecraft": {
                "last_username": "lululombard",
                "previous_username": "LuluQc",
                "provider_display_name": "Minecraft",
                "uuid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
            },
            "discord": {
                "last_username": "lululombard#1337",
                "previous_username": null,
                "provider_display_name": "Discord",
                "uuid": "123456789012345678"
            }
        },
        "attributes": {
            "command_spy": 0
        }
    }

+ Response 404
+ Response 429


### Safe delete Player [DELETE /api/v1/player/{uuid}]

+ Parameters
    + uuid: `minecraft:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX` (string, required) - Regex: `(discord|minecraft|player):(\S*)`

+ Response 200
+ Response 404
+ Response 429


### Update Player [PATCH /api/v1/player/{uuid}]

To update a variable or an object of a player
Can only use the fields to be modified.

+ Parameters
    + uuid: `minecraft:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX` (string, required) - Regex: `(discord|minecraft|player):(\S*)`

+ Request (application/json)
    + Body
    {
        "providers": {
            "discord": {
                "last_username": "NewName#1337",
                "uuid": "123456789012345678"
            }
        }
    }

+ Response 200 (application/json)
    {
        "id": "player:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX",
        "main_language": "EN",
        "languages": [
            "FR",
            "EN"
        ],
        "username": "lululombard",
        "providers": {
            "minecraft": {
                "last_username": "lululombard",
                "previous_username": "LuluQc",
                "provider_display_name": "Minecraft",
                "uuid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
            },
            "discord": {
                "last_username": "NewName#1234",
                "previous_username": "lululombard#1337",
                "provider_display_name": "Discord",
                "uuid": "123456789012345678"
            }
        },
        "attributes": {
            "command_spy": 0
        }
    }

+ Response 404
+ Response 429

### Update Player [PUT /api/v1/player/{uuid}]

Pour update un object joueur entier.
Needs a complete player object.

+ Parameters
    + uuid: `minecraft:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX` (string, required) - Regex: `(discord|minecraft|player):(\S*)`

+ Request (application/json)
    + Body
    {
        "main_language": "EN",
        "languages": [
            "FR",
            "EN"
        ],
        "providers": {
            "minecraft": {
                "last_username": "lululombard",
                "previous_username": "LuluQc",
                "provider_display_name": "Minecraft",
                "uuid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
            },
            "discord": {
                "last_username": "NewName#1234",
                "previous_username": "lululombard#1337",
                "provider_display_name": "Discord",
                "uuid": "123456789012345678"
            }
        },
        "attributes": {
            "command_spy": 0
        }
    }

+ Response 200 (application/json)
    {
        "id": "player:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX",
        "main_language": "EN",
        "languages": [
            "FR",
            "EN"
        ],
        "username": "lululombard",
        "providers": {
            "minecraft": {
                "last_username": "lululombard",
                "previous_username": "LuluQc",
                "provider_display_name": "Minecraft",
                "uuid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
            },
            "discord": {
                "last_username": "NewName#1234",
                "previous_username": "lululombard#1337",
                "provider_display_name": "Discord",
                "uuid": "123456789012345678"
            }
        },
        "attributes": {
            "command_spy": 0
        }
    }

+ Response 404
+ Response 429
